### ISSUE TITLE
Add support for rspec-3.3

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#345]
### TODO:

* [x] Bump dependency
* [x] Add 3.3 specific integration branch
* [x] Test
* [x] Remove 3.0, and 3.1 integration
* [ ] Assuming no breakage: release

**Comment by UrsMetz** [comment]
Is integration for RSpec 3.0 and 3.1 really removed (as indicated by the done TODO item)? The changes in d6b3932 suggest that both versions are stilled supported.
I'm just asking for clarity.

**Comment by mbj** [comment]
@UrsMetz The next commit c5a9ad8a2d45f1ccdeffd9ff520ec34e0b2094c6 removes support for 3.0 and 3.1. I do not use them. And my policy is to only support what I use, and or where support is trivial. It could be argued 3.0 and 3.1 support *is* trivial, but rspec was never easy to interface with (for various reasons, mostly its globals), lowering the amount of rspecs I support frees development, and especially support cycles I can use for more interesting stuff in mutant.

**Comment by UrsMetz** [comment]
@mbj thanks for the fast response. When locking for the rspec version constraints I didn't look at the current version of `mutant-rspec.gemspec` and ` spec/integration/mutant/rspec_spec.rb` but I thought I did. So file this under "layer 8 failure" ;-).

**Comment by mbj** [comment]
@UrsMetz NP, keep your feedback / thoughts coming, it triggers additional thought and self validation cycles on my side that always have a positive effect at some place.
